#!/bin/bash

set -e

pushd `dirname $0` > /dev/null
BOOKWATCH_BIN_PATH=`pwd`
popd > /dev/null

ln -s ${BOOKWATCH_BIN_PATH}/watch /usr/local/bin/
echo "linked ${BOOKWATCH_BIN_PATH}/watch to /usr/local/bin/watch"
